(function(){
 const catalog=window.HANDURO_CATALOG;let current=null,manual=[],removeCustom=()=>{},page=1;
 const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
 const fmt=n=>Number(n).toLocaleString('es-AR',{maximumFractionDigits:2});
 let inventory={};try{inventory=JSON.parse(localStorage.getItem('handuro-inventory-v1'))||{};}catch{}
 const root=document.getElementById('models');
 const selection=document.createElement('section');selection.id='opciones-minimas';selection.className='card selection';selection.setAttribute('tabindex','-1');
 const selectionTitle=el('h2',null,'Bombas de menor potencia para este cálculo');
 const onlyStock=el('input');onlyStock.type='checkbox';onlyStock.id='selectionStock';
 const stockToggle=el('label','stock-toggle','Usar solamente disponibilidad confirmada');stockToggle.prepend(onlyStock);
 const selectionBody=el('div');selection.append(selectionTitle,el('p','hint','“Más pequeñas” significa menor potencia nominal publicada, no menor diámetro. Se exige caudal y altura suficientes en la curva aproximada, fuera de la banda de revisión. Se excluyen los modelos marcados no disponibles.'),stockToggle,selectionBody);
 document.querySelector('.layout').after(selection);onlyStock.onchange=renderSelection;
 const resultLink=el('a','selection-link','Ver bombas de menor potencia y resultado →');resultLink.href='#opciones-minimas';document.querySelector('.result').append(resultLink);
 const recommendationHint=el('p','hint');document.querySelector('.result').append(recommendationHint);
 function renderSelection(){
 selectionBody.replaceChildren();if(!current){recommendationHint.textContent='Completá un cálculo válido para ver las opciones.';selectionBody.append(el('p','empty','No hay un cálculo válido. Revisá los datos ingresados.'));return;}
 const options=smallestPumps(catalog.models,current,inventory,onlyStock.checked);
 const project=document.getElementById('project').value||'Sin nombre';selectionBody.append(el('h3',null,project));
 const summary=el('div','selection-summary');[['Caudal',current.q,'m³/h'],['Altura total',current.head,'m'],['Potencia hidráulica',current.hydraulic,'kW'],['Potencia eléctrica estimada',current.electric,'kW'],['Energía estimada',current.energy,'kWh/día'],['Pérdidas',current.losses,'m']].forEach(([label,n,unit])=>{const item=el('div');item.append(el('span',null,label),el('strong',null,fmt(n)+' '+unit));summary.append(item);});selectionBody.append(summary);
 selectionBody.append(el('p','hint',`Demanda: ${document.getElementById('volume').value} m³/día en ${document.getElementById('hours').value} horas equivalentes. Eficiencia supuesta: ${document.getElementById('efficiency').value} %. La potencia eléctrica calculada es una estimación de consumo; no reemplaza la comprobación Q–H ni define la potencia nominal del motor.`));
 if(!options.length){recommendationHint.textContent='No se encontraron opciones de menor potencia con margen suficiente.';selectionBody.append(el('p','empty',onlyStock.checked?'No hay bombas confirmadas disponibles que superen el criterio hidráulico. Desactivá el filtro para explorar el catálogo.':'Ningún modelo evaluable supera la banda de revisión en este punto. Revisá el catálogo: puede haber casos cercanos al límite o fuera de los puntos digitalizados. No significa que el fabricante no tenga una solución.'));return;}
 const min=options[0].model.powerKW,minimum=options.filter(o=>o.model.powerKW===min),higher=options.filter(o=>o.model.powerKW>min);
 recommendationHint.textContent=`${minimum.length} opciones de ${fmt(min)} kW de potencia nominal mínima en el catálogo evaluable.`;
 selectionBody.append(el('h3',null,`${minimum.length} opciones de menor potencia: ${fmt(min)} kW`));
 selectionBody.append(el('p','hint','Ordenadas por menor exceso de altura dentro de la misma potencia. Esta clasificación no acredita eficiencia óptima, tamaño físico mínimo ni el punto real de operación.'));
 function table(rows){const wrap=el('div','table-scroll'),t=el('table','recommendation-table'),head=el('thead'),tr=el('tr');['Modelo','Potencia nominal','Altura a tu caudal','Exceso de altura','Disponibilidad','Curva'].forEach(x=>tr.append(el('th',null,x)));head.append(tr);t.append(head);const body=el('tbody');rows.forEach(o=>{const m=o.model,r=el('tr');[m.name,fmt(m.powerKW)+' kW','≈ '+fmt(o.height)+' m','≈ '+fmt(o.margin)+' m',(inventory[m.id]==='available'?'Disponible':'Sin confirmar')].forEach(x=>r.append(el('td',null,x)));const td=el('td'),a=el('a','source-link','Ver curva '+m.number);a.href='#models';a.onclick=()=>{search.value=m.name;family.value='';stock.value='';status.value='';page=1;render();const d=list.querySelector('details');if(d)d.open=true;};td.append(a,document.createTextNode(' · '),link('Ficha',m.sourceImage));r.append(td);body.append(r);});t.append(body);wrap.append(t);return wrap;}
 selectionBody.append(table(minimum));if(higher.length){const more=el('details');more.append(el('summary',null,`Ver ${higher.length} alternativas de mayor potencia que también superan el criterio`),table(higher));selectionBody.append(more);}
 selectionBody.append(el('p','warn','Preselección basada en lecturas gráficas aproximadas. Confirmar condiciones de alimentación, rango de operación y producción solar diaria. Los modelos cercanos al límite no se incluyen entre estas opciones.'));
 }
 const controls=el('div','catalog-controls'),search=el('input'),family=el('select'),stock=el('select'),status=el('select');search.type='search';search.placeholder='Buscar modelo o número de curva';search.setAttribute('aria-label','Buscar modelo o número de curva');
 const addOption=(s,value,text)=>{const o=el('option',null,text);o.value=value;s.append(o);};
 addOption(family,'','Todas las familias');[...new Set(catalog.models.map(m=>m.family))].forEach(f=>addOption(family,f,f));family.setAttribute('aria-label','Familia de bomba');
 [['','Toda la disponibilidad'],['available','Disponibles'],['unknown','Sin confirmar'],['unavailable','No disponibles']].forEach(a=>addOption(stock,...a));stock.setAttribute('aria-label','Disponibilidad');
 [['','Todos los resultados'],['candidate','Preselección hidráulica'],['borderline','Cerca del límite'],['insufficient','Altura insuficiente'],['outside','Fuera de los puntos leídos']].forEach(a=>addOption(status,...a));status.setAttribute('aria-label','Resultado hidráulico');
 controls.append(search,family,stock,status);const count=el('p','hint'),list=el('div'),pager=el('div','pager');root.append(controls,count,list,pager);
 [search,family,stock,status].forEach(n=>n.addEventListener('input',()=>{page=1;render();}));
 function assess(m){if(!current)return {key:'outside',text:'Completá los datos de la instalación.'};const h=interpolate(m.points,current.q);if(h===null)return {key:'outside',text:'Caudal fuera del intervalo de puntos leídos. Consultar gráfico original.'};const band=m.quality==='graphical'?m.readingBand:0;const delta=h-current.head;return {h,band,delta,key:delta>band?'candidate':delta< -band?'insufficient':'borderline',text:delta>band?'Preselección hidráulica · verificar operación y energía':delta< -band?'Altura insuficiente al caudal solicitado':'Cerca del límite · confirmar con fabricante'};}
 function link(text,url){const a=el('a','source-link',text);a.href=url;a.target='_blank';a.rel='noopener';return a;}
 function chart(m){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 620 300');svg.setAttribute('role','img');svg.setAttribute('aria-label','Curva aproximada de '+m.name+' y punto solicitado');
 const maxQ=Math.max(m.maxFlow||m.points.at(-1)[0],current?.q||0)*1.1,maxH=Math.max(m.maxHead||m.points[0][1],current?.head||0)*1.12;
 const X=q=>58+q/maxQ*535,Y=h=>252-h/maxH*220;
 function shape(tag,attrs,text){const n=document.createElementNS(svg.namespaceURI,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));if(text)n.textContent=text;svg.append(n);return n;}
 for(let i=0;i<=4;i++){const q=maxQ*i/4,h=maxH*i/4;shape('line',{x1:X(q),x2:X(q),y1:32,y2:252,stroke:'#e2ebef'});shape('line',{x1:58,x2:593,y1:Y(h),y2:Y(h),stroke:'#e2ebef'});shape('text',{x:X(q),y:273,'text-anchor':'middle',fill:'#58717f','font-size':11},fmt(q));shape('text',{x:50,y:Y(h)+4,'text-anchor':'end',fill:'#58717f','font-size':11},fmt(h));}
 shape('text',{x:320,y:295,'text-anchor':'middle','font-size':12,fill:'#19384a'},'Caudal · m³/h');shape('text',{x:58,y:20,'font-size':12,fill:'#19384a'},'Altura · m');
 shape('polyline',{points:m.points.map(([q,h])=>`${X(q)},${Y(h)}`).join(' '),fill:'none',stroke:'#058ea3','stroke-width':3});m.points.forEach(([q,h])=>shape('circle',{cx:X(q),cy:Y(h),r:3,fill:'#058ea3'}));
 if(current){shape('circle',{cx:X(current.q),cy:Y(current.head),r:6,fill:'#df8229',stroke:'white','stroke-width':2});}
 return svg;}
 function render(){renderSelection();list.replaceChildren();pager.replaceChildren();const all=[...catalog.models,...manual.map((m,i)=>({...m,id:'custom-'+i,number:'Personalizada',family:'Personalizada',customIndex:i}))];
 const matches=all.filter(m=>(!family.value||m.family===family.value)&&(!stock.value||(inventory[m.id]||'unknown')===stock.value)&&(!search.value||(m.name+' '+m.number).toLowerCase().includes(search.value.toLowerCase()))).map(m=>({m,a:assess(m)})).filter(({a})=>!status.value||status.value===a.key);
 const order={candidate:0,borderline:1,insufficient:2,outside:3};matches.sort((a,b)=>order[a.a.key]-order[b.a.key]||Math.abs(a.a.delta??Infinity)-Math.abs(b.a.delta??Infinity)||(Number(a.m.number)-Number(b.m.number)));
 const pages=Math.max(1,Math.ceil(matches.length/12));page=Math.min(page,pages);count.textContent=`${matches.length} resultados · ${catalog.models.length} modelos del catálogo oficial · ${catalog.sheets.length} fichas · página ${page} de ${pages}. Disponibilidad sin confirmar por defecto.`;
 if(!matches.length)list.append(el('div','empty','No hay modelos con estos filtros. Probá otra familia o ampliá la búsqueda.'));
 matches.slice((page-1)*12,page*12).forEach(({m,a})=>{const card=el('article','model');const top=el('div','model-top');const title=el('h3',null,m.name),badge=el('span','badge','Curva '+m.number);top.append(title,badge);card.append(top);
 if(m.powerKW)card.append(el('p','hint',`${m.family} · Potencia de tabla: ${fmt(m.powerKW)} kW · Qmáx: ${fmt(m.maxFlow)} m³/h · Hmáx: ${fmt(m.maxHead)} m · valores máximos no simultáneos`));
 card.append(el('span','status '+a.key,a.text));if(a.h!==undefined)card.append(el('p',null,`A ${fmt(current.q)} m³/h: altura leída ≈ ${fmt(a.h)} m; altura requerida ${fmt(current.head)} m.${a.band?' Banda de revisión: ±'+fmt(a.band)+' m.':''}`));
 const stockLabel=el('label',null,'Disponibilidad de este modelo');const select=el('select');select.setAttribute('aria-label','Disponibilidad '+m.name);[['unknown','Sin confirmar'],['available','Disponible'],['unavailable','No disponible']].forEach(o=>addOption(select,...o));select.value=inventory[m.id]||'unknown';select.onchange=()=>{inventory[m.id]=select.value;try{localStorage.setItem('handuro-inventory-v1',JSON.stringify(inventory));}catch{}render();};stockLabel.append(select);card.append(stockLabel);
 const details=el('details');details.append(el('summary',null,'Ver curva y datos de origen'));details.addEventListener('toggle',()=>{if(details.open&&!details.dataset.loaded){details.dataset.loaded='true';details.append(chart(m));details.append(el('p','hint','Línea azul: puntos leídos e interpolados. Punto naranja: demanda de la instalación. No se extrapola fuera de los puntos.'));details.append(el('p','hint',m.condition));
 if(m.sourceNote)details.append(el('p','warn',m.sourceNote));if(m.quality==='graphical'){details.append(el('p','hint','Lectura visual aproximada. La banda de revisión es un criterio de la app (máximo de 5 m y 5% de Hmáx), no una tolerancia certificada ni una garantía de error. La ficha no indica un rango de operación recomendado ni condiciones de ensayo.'));details.append(link('Abrir ficha original guardada',m.sourceImage),document.createTextNode(' · '),link('Página oficial Handuro',m.source));}
 else details.append(el('p','hint','Fuente: '+m.source));
 const table=el('table','points-table'),thead=el('thead'),tr=el('tr');['Caudal m³/h','Altura m'].forEach(t=>tr.append(el('th',null,t)));thead.append(tr);table.append(thead);const tbody=el('tbody');m.points.forEach(p=>{const r=el('tr');p.forEach(v=>r.append(el('td',null,fmt(v))));tbody.append(r);});table.append(tbody);details.append(table);}});card.append(details);
 if(m.customIndex!==undefined){const b=el('button',null,'Quitar curva personalizada');b.onclick=()=>removeCustom(m.customIndex);card.append(b);}list.append(card);});
 const prev=el('button',null,'← Anterior'),next=el('button',null,'Siguiente →');prev.disabled=page<=1;next.disabled=page>=pages;prev.onclick=()=>{page--;render();root.scrollIntoView({behavior:'smooth'});};next.onclick=()=>{page++;render();root.scrollIntoView({behavior:'smooth'});};pager.append(prev,el('span',null,`${page} / ${pages}`),next);
 }
 const library=document.getElementById('sourceLibrary');catalog.sheets.forEach(s=>{const item=el('details','sheet');item.append(el('summary',null,s.title));const image=el('img');image.src=s.image.file;image.loading='lazy';image.alt='Curvas y tabla técnica '+s.title;item.append(link('Abrir imagen a tamaño completo',s.image.file),document.createTextNode(' · '),link('Ver publicación oficial',s.url),image);library.append(item);});
 window.renderHanduroCatalog=(r,custom,remove)=>{current=r;manual=custom;removeCustom=remove;render();};
})();

